var tree = [["Bbatsche",,"",
                [["Entrust","Bbatsche\/Entrust.html","",
                [["Contracts","Bbatsche\/Entrust\/Contracts.html","",
                [["EntrustPermissionInterface","Bbatsche\/Entrust\/Contracts\/EntrustPermissionInterface.html","",
                [        ]],["EntrustRoleInterface","Bbatsche\/Entrust\/Contracts\/EntrustRoleInterface.html","",
                [        ]],["EntrustUserInterface","Bbatsche\/Entrust\/Contracts\/EntrustUserInterface.html","",
                [        ]]        ]],["Traits","Bbatsche\/Entrust\/Traits.html","",
                [["EntrustPermissionTrait","Bbatsche\/Entrust\/Traits\/EntrustPermissionTrait.html","",
                [        ]],["EntrustRoleTrait","Bbatsche\/Entrust\/Traits\/EntrustRoleTrait.html","",
                [        ]],["EntrustUserTrait","Bbatsche\/Entrust\/Traits\/EntrustUserTrait.html","",
                [        ]]        ]],["Entrust","Bbatsche\/Entrust\/Entrust.html","",
                [        ]],["EntrustFacade","Bbatsche\/Entrust\/EntrustFacade.html"," < Facade",
                [        ]],["EntrustPermission","Bbatsche\/Entrust\/EntrustPermission.html"," < Model",
                [        ]],["EntrustRole","Bbatsche\/Entrust\/EntrustRole.html"," < Model",
                [        ]],["EntrustServiceProvider","Bbatsche\/Entrust\/EntrustServiceProvider.html"," < ServiceProvider",
                [        ]],["HasRole","Bbatsche\/Entrust\/HasRole.html","",
                [        ]],["MigrationCommand","Bbatsche\/Entrust\/MigrationCommand.html"," < Command",
                [        ]]        ]]        ]]        ]

